spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB
  datasource:
    url: jdbc:mysql://localhost:3306/springai?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: sprint-demo
  ai:
    openai:
      api-key: <api-key>
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-flash
      embedding:
        options:
          model: text-embedding-v1
server:
  port: 8080
logging:
  level:
    org.springframework.ai: debug # AI对话的日志级别
    com.zlq.springaidemo: debug

